### PR TITLE
Final project

### PR DESCRIPTION
**Pull request by hammaazarok**
# In this Project I have achieved the following :

- Set up the repository and tools.
- Created models according to the ERD diagram. 
- Implement the authentication and authorization.
- Created the page to add a category.
- Created the home page.
- Created the page to add a transaction.
- Created the transactions page.
- Added validations unit test and integration tests.
- Deployed the project, and tested for final details.
- Recorded a video for the project.
- Created a good README and PR description.

## here is a link to the [Presentation](https://www.loom.com/share/56f2d36372dd4c3890f2167de161d95a) video

### CODE REVIEW

**Review by mukhammadrizooff — CHANGES_REQUESTED** [review]
Hi @hammaazarok, 

Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.



## Highlights
- No linter errors ✔️ 
- Good implementations ✔️ 
- Descriptive `PR` description and commit history ✔️ 

## Suggested changes
- [ ] [REQUIRED] Good job so far👍 You did a great job, but I think you forgot to fulfill one of the requirement mentioned. Accordingly, in your [presentation video](https://www.loom.com/share/56f2d36372dd4c3890f2167de161d95a) should have `highlight about a piece of the code in the project you find interesting or proud of making in your codebase`. You have made a great presentation video but the above mentioned `requirement` is not fulfilled in the video, please `re-record` your project presentation video with the given requirement and update the link on your `PR` description when you will have finish 🙏🙏🙏 

image

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by hammaazarok** [comment]
Hello @mukhammadrizooff 
Thanks for the review but I have to disagree with you on this because I don't think there is a need for me to re-record the video as it is required to mention a piece of code or something you built (a feature) you are proud of and it is present in the video from minute 3:33 to 4:05.

**Review by Danieldotcomcoder — APPROVED** [review]
Hello @hammaazarok , 

Your project is complete!  There is nothing else to say other than... it's time to merge it 👍 👍 😄 👏 

Congratulations! 🎉 🎉 🎉 

## Highlights
- Professional Readme File ✔✔
- Linters are setup correctly ✔✔
- Clear and nice code ✔✔

comp-2
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by hammaazarok** [comment]
@Danieldotcomcoder thanks for the review.

**Pull request merged**
